### ISSUE TITLE
APP下载后手机无法使用？

### ISSUE THREAD

**Issue by wuzhixian2016** [dPary/Ion2#1]
你好，我下载了你的APP后打开不能使用啊，除了中间可以滚动之外，其他地方点击都没有反应
![image](https://cloud.githubusercontent.com/assets/20715683/21840443/889b0bd4-d818-11e6-9f3e-a29d7dfe2e61.png)

**Comment by git-liyou** [comment]
安卓版本？

**Comment by git-liyou** [comment]
APP设置兼容至Android4.4，Android4.4以下安装会解析失败，但是应用宝会直接安装成功，所以会出现你的情况，添加crosswalk可兼容至Android4.1，请自行测试。

**Comment by wuzhixian2016** [comment]
谢谢回答，应该是版本问题，我的是Android4.2的，还有个问题是，我把项目clone到本地后如何运行呢？之前用的都是ionic1的模板，只要ionic serve就行，现在的ionic2不熟悉

**Comment by git-liyou** [comment]
@wuzhixian1016 确保ionic cli为2.0+，新建ionic2的项目，替换src，执行ionic serve即可
